version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: claude-company-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: claude_company
      POSTGRES_USER: claude_user
      POSTGRES_PASSWORD: claude_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude_user -d claude_company"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: claude-company-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@claude-company.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: